export enum ReportReason {
    SPAM = 'SPAM',
    HARASSMENT_OR_HATE = 'HARASSMENT_OR_HATE',
    INAPPROPRIATE_CONTENT = 'INAPPROPRIATE_CONTENT',
    FAKE_ACCOUNT = 'FAKE_ACCOUNT',
    OTHER = 'OTHER'
  }